spring:
  datasource:
    url: -- database UR
    username: -- database user
    password: -- database pswd
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate: {show_sql: true, use_sql_comments: true, format_sql: true}
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
twitter4j:
  oauth:
    access-token: -- add your key
    access-token-secret: -- add your key
    consumer-key: -- add your key
    consumer-secret: -- add your key
cloud:
  aws:
    region:
      static: us-east-1